title: Settings
fields:
  -
    handle: debug
    field:
      type: toggle
      display: Debug
  -
    handle: template
    field:
      type: template
      display: Template
  -
    handle: layout
    field:
      type: template
      display: Layout
  -
    handle: page_class
    field:
      options:
        privacy: Datenschutz
        imprint: Impressum
      type: select
      display: 'Seiten CSS-Klasse'
